version: '3'

services:
  web:
    environment:
    - APACHE_RUN_USER=#1000
    build:
      context: ./docker/web
    ports:
      - 10000:80
    volumes:
      - ./src/:/var/www/html
    networks:
      - app-network

  database:
    image: mariadb
    container_name: database
    restart: unless-stopped
    ports:
    - 33061:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    networks:
      - app-network        
#Docker Networks
networks:
  app-network:
    driver: bridge      